upstream fastcgi_backend {
    server php:9000;
}

server {
    listen 80;
    server_name magento-enterprise.local;

    set $MAGE_ROOT /var/www/html;
    set $MAGE_MODE developer;

    root $MAGE_ROOT/pub;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /static/ {

        location ~ ^/static/version {
            rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
        }

        try_files $uri $uri/ /static.php?resource=$uri&$args;

        expires max;
        add_header Cache-Control public;
    }

    location /media/ {
        try_files $uri $uri/ /get.php?$args;
    }

    location ~ \.php$ {
    fastcgi_pass fastcgi_backend;
    fastcgi_index index.php;

    include fastcgi_params;

    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param MAGE_MODE developer;

    fastcgi_read_timeout 600;

    fastcgi_buffer_size 256k;
    fastcgi_buffers 16 256k;
    fastcgi_busy_buffers_size 512k;
}
}
